In [1]:
import sys
sys.path.append('/home/mila/l/leo.gagnon/latent_control')

%load_ext autoreload
%autoreload 2
from lightning_modules.diffusion_prior import DiffusionPriorTask
import torch
import matplotlib.pyplot as plt
from data.diffusion import KnownLatentDiffusionDataset
from torch2jax import j2t, t2j

In [114]:
task = DiffusionPriorTask('70gkb6eh')
task.cuda();

Loaded dataset : (11288/1000)
Loaded checkpoing : last.ckpt
Loaded checkpoing : last.ckpt


In [115]:
seq = task.base_task.full_data.__getitems__([0])['input_ids']

/home/mila/l/leo.gagnon/latent_control/data/hmm.py:585: FutureWarning: None encountered in jnp.array(); this is currently treated as NaN. In the future this will result in an error.
  intv_envs = jnp.array(intv_envs)


In [116]:
dataset = task.train_data.dataset 
dataset: KnownLatentDiffusionDataset

In [122]:
dataset[0]

/home/mila/l/leo.gagnon/latent_control/data/hmm.py:585: FutureWarning: None encountered in jnp.array(); this is currently treated as NaN. In the future this will result in an error.
  intv_envs = jnp.array(intv_envs)


{'latent': tensor([[[ 1.5561e+00,  7.4856e-01,  4.1153e+00, -2.4731e+00, -1.4466e+00,
           -1.2991e+00,  1.7986e+00, -4.4539e+00,  4.6276e+00, -1.2840e+00,
            2.8628e+00, -3.8792e+00, -5.9071e-01, -3.0843e+00, -1.9485e+00,
           -5.2641e+00, -2.8646e+00, -7.0337e-01, -1.9427e+00, -4.3665e-02,
           -3.2926e+00,  7.2712e+00, -2.4647e+00, -3.3398e-01, -9.0019e-01,
            2.2383e+00, -1.4827e+00, -5.2373e+00, -1.0177e+00,  8.3677e-01,
            1.1302e+00,  2.2745e-01, -8.5907e-01, -9.6679e-02,  1.4911e+00,
           -2.5468e+00, -2.5649e-01,  1.3726e+00,  1.0484e+00,  5.3324e+00,
            2.2521e+00, -2.0496e-01, -2.1855e+00,  9.1902e-01,  1.8415e+00,
           -8.1387e-02, -3.7777e-01, -5.3471e+00,  1.3217e+00, -1.6922e+00,
           -8.1620e-02,  1.1876e+00, -3.2295e+00,  4.5442e-01, -2.4309e+00,
           -2.0893e+00, -1.1472e-01,  7.5290e-01, -6.6094e-01, -5.4295e+00,
           -1.5896e+00, -8.8771e-01,  1.8211e+00, -2.7817e-01, -3.2782e+00,
  

In [136]:
cond_tokens = dataset.encode(seq).cuda()
cond_mask = torch.BoolTensor([True]*200)[None].cuda()

In [137]:
z_t = task.diffusion_prior.sample(10, cond_tokens=cond_tokens, cond_mask=cond_mask, l2_normalize=False)
#z_t = task.diffusion_prior.unnormalize_latent(z_t)

sampling loop time step:   0%|          | 0/250 [00:00<?, ?it/s]

In [138]:
z_t

tensor([[[ 0.2155, -2.5311,  3.0560,  ...,  1.8253, -1.5975,  0.7164]],

        [[-1.3962,  2.5083,  3.5303,  ...,  3.0101, -0.7180,  1.0073]],

        [[-2.7361, -2.3429,  3.9418,  ...,  1.5526, -1.9551,  0.8898]],

        ...,

        [[ 0.8518,  0.7984,  1.2536,  ...,  3.6575, -2.6872,  2.6288]],

        [[-0.9345,  2.7147,  0.0268,  ...,  6.0019,  1.4886,  3.5353]],

        [[ 0.2462, -3.5709,  3.5764,  ...,  2.7586,  2.0837,  2.2972]]],
       device='cuda:0')

In [124]:
dataset[0]

{'latent': tensor([[[ 1.5561e+00,  7.4856e-01,  4.1153e+00, -2.4731e+00, -1.4466e+00,
           -1.2991e+00,  1.7986e+00, -4.4539e+00,  4.6276e+00, -1.2840e+00,
            2.8628e+00, -3.8792e+00, -5.9071e-01, -3.0843e+00, -1.9485e+00,
           -5.2641e+00, -2.8646e+00, -7.0337e-01, -1.9427e+00, -4.3665e-02,
           -3.2926e+00,  7.2712e+00, -2.4647e+00, -3.3398e-01, -9.0019e-01,
            2.2383e+00, -1.4827e+00, -5.2373e+00, -1.0177e+00,  8.3677e-01,
            1.1302e+00,  2.2745e-01, -8.5907e-01, -9.6679e-02,  1.4911e+00,
           -2.5468e+00, -2.5649e-01,  1.3726e+00,  1.0484e+00,  5.3324e+00,
            2.2521e+00, -2.0496e-01, -2.1855e+00,  9.1902e-01,  1.8415e+00,
           -8.1387e-02, -3.7777e-01, -5.3471e+00,  1.3217e+00, -1.6922e+00,
           -8.1620e-02,  1.1876e+00, -3.2295e+00,  4.5442e-01, -2.4309e+00,
           -2.0893e+00, -1.1472e-01,  7.5290e-01, -6.6094e-01, -5.4295e+00,
           -1.5896e+00, -8.8771e-01,  1.8211e+00, -2.7817e-01, -3.2782e+00,
  

In [126]:
env_latents = j2t(task.base_task.full_data.index_to_latent)[0].to(torch.long).cuda()[None]
env_latents = task.base_task.model.encoder(true_latents=env_latents)
env_latents

tensor([[[ 1.5561e+00,  7.4856e-01,  4.1153e+00, -2.4731e+00, -1.4466e+00,
          -1.2991e+00,  1.7986e+00, -4.4539e+00,  4.6276e+00, -1.2840e+00,
           2.8628e+00, -3.8792e+00, -5.9071e-01, -3.0843e+00, -1.9485e+00,
          -5.2641e+00, -2.8646e+00, -7.0337e-01, -1.9427e+00, -4.3665e-02,
          -3.2926e+00,  7.2712e+00, -2.4647e+00, -3.3398e-01, -9.0019e-01,
           2.2383e+00, -1.4827e+00, -5.2373e+00, -1.0177e+00,  8.3677e-01,
           1.1302e+00,  2.2745e-01, -8.5907e-01, -9.6679e-02,  1.4911e+00,
          -2.5468e+00, -2.5649e-01,  1.3726e+00,  1.0484e+00,  5.3324e+00,
           2.2521e+00, -2.0496e-01, -2.1855e+00,  9.1902e-01,  1.8415e+00,
          -8.1387e-02, -3.7777e-01, -5.3471e+00,  1.3217e+00, -1.6922e+00,
          -8.1620e-02,  1.1876e+00, -3.2295e+00,  4.5442e-01, -2.4309e+00,
          -2.0893e+00, -1.1472e-01,  7.5290e-01, -6.6094e-01, -5.4295e+00,
          -1.5896e+00, -8.8771e-01,  1.8211e+00, -2.7817e-01, -3.2782e+00,
           4.9800e-01,  1

In [95]:
task.base_task.model.encoder.latent_embedding[3].weight @ z_t[0].T

tensor([[ 179.3701],
        [-104.5878]], device='cuda:0')

In [19]:
task.base_task.model.encoder.latent_embedding[1].weight @ z_t[0].T

tensor([[189.8581],
        [ -6.5179]], device='cuda:0')

In [31]:
task.base_task.full_data.index_to_latent[0]

Array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [139]:
[torch.Tensor([(latent_embds.weight @ z_t[i].T).argmax() for latent_embds in task.base_task.model.encoder.latent_embedding]) for i in range(10)]

[tensor([2., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 2.]),
 tensor([2., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 2.]),
 tensor([3., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([3., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([3., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 2.]),
 tensor([0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([3., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2.]),
 tensor([1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 2.]),
 tensor([0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])]