In [15]:
import sys
sys.path.append('/home/mila/l/leo.gagnon/latent_control')

%load_ext autoreload
%autoreload 2

from tasks.metalearn import MetaLearningTask, MetaLearningConfig
from models.decoder import TransformerDecoder, TransformerDecoderConfig
from tasks.dsm_diffusion import DSMDiffusion

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [8]:
a = {1: 2, 3:4}
a.update({'lol': 'xd'})

In [1]:
import torch

In [25]:
torch.arange(10)[1:-2:2]

tensor([1, 3, 5, 7])

In [2]:
a = torch.Tensor([[1,2,3], [4,5,6]])
b = torch.Tensor([0,0,0])

In [26]:
x, d = a.shape

In [27]:
x,d

(2, 3)

In [14]:
torch.index_select(a, -1, torch.LongTensor([0]))

tensor([[1.],
        [4.]])

In [6]:
torch.gather(a, 0, torch.LongTensor([0,1]))

RuntimeError: Index tensor must have the same number of dimensions as input tensor

In [7]:
a.shape

torch.Size([2, 3])

In [19]:
from enum import Enum

In [36]:
for i in Enum('xd', {'HI': 0, 'BYE': 1}):
    print(i)

xd.HI
xd.BYE


In [13]:
from einops import rearrange, repeat

In [33]:
rearrange([a, repeat(b, 'l -> b l', b=2)], 't b l -> b (l t)')

tensor([[1., 0., 2., 0., 3., 0.],
        [4., 0., 5., 0., 6., 0.]])

In [31]:
torch.repeat_interleave(torch.Tensor([1,2,3]),2)

tensor([1., 1., 2., 2., 3., 3.])

In [37]:
task = DSMDiffusion.load_from_checkpoint(
    "/network/scratch/l/leo.gagnon/latent_control_log/checkpoints/f3oppg5h/last.ckpt", strict=False
)
task.cuda();

/home/mila/l/leo.gagnon/latent_control/venv/lib/python3.10/site-packages/lightning/pytorch/core/saving.py:191: Found keys that are in the model state dict but not in the checkpoint: ['seen_tokens', 'val_latents', 'train_latents']
/home/mila/l/leo.gagnon/latent_control/venv/lib/python3.10/site-packages/lightning/pytorch/core/saving.py:191: Found keys that are in the model state dict but not in the checkpoint: ['seen_tokens', 'val_latents', 'train_latents']
/home/mila/l/leo.gagnon/latent_control/venv/lib/python3.10/site-packages/lightning/pytorch/core/saving.py:191: Found keys that are in the model state dict but not in the checkpoint: ['seen_tokens', 'val_latents', 'train_latents']


In [28]:
del task

In [5]:
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

In [39]:
xd = TransformerDecoder(TransformerDecoderConfig(300,50,15,8,1024))

In [55]:
xd.attn_layers.layers[0][1].to_q.weight.dtype

torch.float32

In [41]:
count_parameters(xd) / 1000000

157.497345

In [ ]:
_target_: models.decoder.TransformerDecoder
  max_seq_len: 300
  num_tokens : ${eval:'${task.metalearn.data.n_obs} + 1'}
  n_layer: 10
  n_head: 8
  n_embd: 512
  positional_encodings: True

In [4]:
task = MetaLearningTask.from_id('8jzqijc5')

In [19]:
path = '/'.join([task.wandb_dict['ckpts_dir'], task.wandb_dict['ckpts_names'][0]])

In [20]:
MetaLearningTask.load_from_checkpoint(path)

MetaLearningTask(
  (model): MetaLearner(
    (decoder): TransformerDecoder(
      (token_emb): TokenEmbedding(
        (emb): Embedding(51, 384)
      )
      (pos_emb): ScaledSinusoidalEmbedding()
      (post_emb_norm): Identity()
      (emb_dropout): Dropout(p=0.0, inplace=False)
      (project_emb): Identity()
      (attn_layers): Decoder(
        (layers): ModuleList(
          (0): ModuleList(
            (0): ModuleList(
              (0): LayerNorm(
                (ln): LayerNorm((384,), eps=1e-05, elementwise_affine=False)
              )
              (1-2): 2 x None
            )
            (1): Attention(
              (to_q): Linear(in_features=384, out_features=512, bias=False)
              (to_k): Linear(in_features=384, out_features=512, bias=False)
              (to_v): Linear(in_features=384, out_features=512, bias=False)
              (split_q_heads): Rearrange('b n (h d) -> b h n d', h=8)
              (split_k_heads): Rearrange('b n (h d) -> b h n d', d=64)
    

In [14]:
class A:
    d = 10
    def __init__(self, a):
        self.a = a
    
    def xd(self):
        return self.__class__

class B(A):
    pass

In [15]:
A.d

10

In [ ]:
b.xd()